# Generated by Django 5.0.2 on 2024-03-04 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-publish_date']},
        ),
    ]
