# Generated by Django 5.0.2 on 2024-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
