# Generated by Django 5.0.2 on 2024-03-09 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_publish_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
