# Generated by Django 5.0.2 on 2024-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_publish_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
    ]
