# Generated by Django 5.0.2 on 2024-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_publish_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
