# Generated by Django 5.0.2 on 2024-03-10 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_publish_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
