# Generated by Django 5.0.2 on 2024-03-24 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_publish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
