# Generated by Django 5.0.2 on 2024-03-25 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_comments_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='file2',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
