# Generated by Django 5.0.2 on 2024-05-27 11:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_studies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='studies',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studies',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
