# Generated by Django 5.0.2 on 2024-05-27 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_studies_options_studies_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={},
        ),
        migrations.AddField(
            model_name='studies',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
