# Generated by Django 5.0.2 on 2024-11-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_studies_options_studies_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studies',
            options={'ordering': ['publish_date']},
        ),
    ]
